# -*- coding: utf-8 -*-
"""gold_price_pred.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19-dDMR6IIgOfL8BTmcSl_coVVn7M17hb
"""

!pip install prophet

from prophet import Prophet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.head()

df.tail()

df.describe()

df.shape

Date = df['Date']
Gold_Price_INR = df['Gold Price in INR']
df['Year'] = pd.to_datetime(df['Date']).dt.year

import seaborn as sns
correlation_matrix = df.corr()

# Create a heatmap of the correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap=sns.cubehelix_palette(20, light=0.75, dark=0.15))

# Set the title of the heatmap
plt.title('Correlation Matrix')

# Show the plot
plt.show()

plt.plot(Date, Gold_Price_INR)

# Customize the graph if needed (e.g., labels, title, etc.)
plt.xlabel('Date')
plt.ylabel('Gold Price in INR')
plt.title('Gold Price in INR Over Time')

# Display the graph
plt.show()

plt.plot(df['Year'], df['Gold Price in INR'])

plt.xlabel('Year')
plt.ylabel('Gold Price in INR')
plt.title('Gold Price in INR Over Time')

plt.show()

# Rename the columns to 'ds' and 'y' for Prophet
df = df.rename(columns={'Date': 'ds', 'Gold Price in INR': 'y'})

model = Prophet()
model.fit(df)

future_dates = model.make_future_dataframe(periods=365)  # Adjust the number of periods as needed

forecast = model.predict(future_dates)

model.plot(forecast)
plt.xlabel('Year')
plt.ylabel('Gold Price in INR')
plt.title('Gold Price Prediction')
plt.show()

forecast_summary = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10)

print(forecast_summary)

fig = model.plot_components(forecast)
plt.show()

"""####Evaluation

"""

actual_values = df['y'].values
predicted_values = forecast['yhat'].values[:len(df)]

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(actual_values, predicted_values)
print("Mean Absolute Error (MAE):", mae)